import { ChangeDetectionStrategy, Component, inject, signal } from "@angular/core";
import { FormBuilder, ReactiveFormsModule, Validators } from "@angular/forms";
import { Router } from "@angular/router";

import { JslibModule } from "@bitwarden/angular/jslib.module";
import { I18nService } from "@bitwarden/common/platform/abstractions/i18n.service";
import { LogService } from "@bitwarden/common/platform/abstractions/log.service";
import {
  ButtonModule,
  CardComponent,
  FormFieldModule,
  InputModule,
  Option,
  SelectModule,
  ToastService,
} from "@bitwarden/components";

import { PopOutComponent } from "../../platform/popup/components/pop-out.component";
import { PopupHeaderComponent } from "../../platform/popup/layout/popup-header.component";
import { PopupPageComponent } from "../../platform/popup/layout/popup-page.component";

import { PersonaLayer, PersonaService } from "./services/persona.service";

/**
 * Black Mask "Create persona" form (M1). Creates an Identity cipher tagged with a layer and,
 * optionally, an email alias generated by the user's configured forwarder. Gated behind the
 * `black-mask-persona-vault` feature flag at the route level.
 */
@Component({
  templateUrl: "./create-persona.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    JslibModule,
    ReactiveFormsModule,
    PopupPageComponent,
    PopupHeaderComponent,
    PopOutComponent,
    CardComponent,
    FormFieldModule,
    InputModule,
    SelectModule,
    ButtonModule,
  ],
})
export class CreatePersonaComponent {
  private readonly formBuilder = inject(FormBuilder);
  private readonly personaService = inject(PersonaService);
  private readonly toastService = inject(ToastService);
  private readonly i18nService = inject(I18nService);
  private readonly logService = inject(LogService);
  private readonly router = inject(Router);

  protected readonly loading = signal(false);
  protected readonly generatingAlias = signal(false);

  protected readonly form = this.formBuilder.group({
    layer: this.formBuilder.control<PersonaLayer>(PersonaLayer.Anonymous, {
      nonNullable: true,
      validators: Validators.required,
    }),
    name: this.formBuilder.control("", { nonNullable: true, validators: Validators.required }),
    email: this.formBuilder.control("", { nonNullable: true }),
    notes: this.formBuilder.control("", { nonNullable: true }),
  });

  protected readonly layerOptions: Option<PersonaLayer>[] = [
    { value: PersonaLayer.Real, label: this.i18nService.t("blackMaskLayerReal") },
    { value: PersonaLayer.Business, label: this.i18nService.t("blackMaskLayerBusiness") },
    { value: PersonaLayer.Creator, label: this.i18nService.t("blackMaskLayerCreator") },
    { value: PersonaLayer.Anonymous, label: this.i18nService.t("blackMaskLayerAnonymous") },
  ];

  protected async generateAlias(): Promise<void> {
    this.generatingAlias.set(true);
    try {
      const alias = await this.personaService.generateAlias();
      this.form.controls.email.setValue(alias);
      this.toastService.showToast({
        variant: "success",
        title: "",
        message: this.i18nService.t("blackMaskAliasGenerated"),
      });
    } catch (e) {
      this.logService.error(e);
      this.toastService.showToast({
        variant: "error",
        title: "",
        message: this.i18nService.t("blackMaskAliasError"),
      });
    } finally {
      this.generatingAlias.set(false);
    }
  }

  protected async submit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.loading.set(true);
    try {
      const value = this.form.getRawValue();
      await this.personaService.createPersona({
        name: value.name,
        layer: value.layer,
        email: value.email || undefined,
        notes: value.notes || undefined,
      });
      this.toastService.showToast({
        variant: "success",
        title: "",
        message: this.i18nService.t("blackMaskPersonaCreated"),
      });
      await this.router.navigate(["/personas"]);
    } catch (e) {
      this.logService.error(e);
      this.toastService.showToast({
        variant: "error",
        title: "",
        message: this.i18nService.t("errorOccurred"),
      });
    } finally {
      this.loading.set(false);
    }
  }
}
